source 'https://rubygems.org'

gem "bcrypt", "~> 3.1.10"
gem "em-websocket", "~> 0.5.1"
gem "jwt", "~> 1.5.2"
gem "pg", "~> 0.18.2"
gem "sequel", "~> 4.25.0"

group :development do
  gem "pry-byebug"
end

group :test do
  gem "database_cleaner", "~> 1.5.1"
  gem "factory_girl", "~> 4.5.0"
  gem "rspec", "~> 3.4.0"
end
