export const THINGS_SET = 'THINGS_SET'
export const THING_CREATE = 'THING_CREATE'
export const THING_UPDATE = 'THING_UPDATE'
export const THING_DELETE = 'THING_DELETE'
export const USERS_OWN_ID = 'USERS_OWN_ID'
export const USERS_SET = 'USERS_SET'
